title: SULI Mini-Seminar 2023 - CROCUS Air Quality Investigation
author: Joe O'Brien
logo: /images/CROCUS_Logo.svg
execute:
  execute_notebooks: cache
  timeout: 600
  allow_errors: False # cells with expected failures must set the `raises-exception` cell tag
parse:
  myst_enable_extensions:
    - html_image
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution
html:
  comments:
    hypothesis: true
repository:
  url: https://github.com/jrobrien91/suli-mini-seminar-2023.git  # Online location of your book
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  jupyterhub_url: https://jupyterhub.arm.gov
  binderhub_url: http://binder.mypythia.org
  notebook_interface: jupyterlab
